GPT-2:
  model_config:
    d_attention: 768
    d_qkv: 64
    d_ff: 3072
    n_layers: 12
    max_ctx: 512
  train_config:
    batch_size: 32
    loss: 'CE'
    lr: 0.0006
    beta_linear: 0.9
    beta_square: 0.95
    weight_decay: 0.01
    n_epochs: 40
    wu_fraction: 0.03
  tokenizer: 'tiktoken'